-- Emma Hud Space database setup for Supabase
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  avatar_url text,
  is_online boolean default false,
  last_seen timestamptz default now(),
  created_at timestamptz default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  type text not null default 'text' check (type in ('text','image','voice','sticker')),
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;

create policy "profiles readable by signed in users" on public.profiles for select to authenticated using (true);
create policy "users insert own profile" on public.profiles for insert to authenticated with check (auth.uid()=id);
create policy "users update own profile" on public.profiles for update to authenticated using (auth.uid()=id);

create policy "messages readable by participants" on public.messages for select to authenticated
using (auth.uid()=sender_id or auth.uid()=receiver_id);
create policy "users send messages" on public.messages for insert to authenticated
with check (auth.uid()=sender_id);

-- Create a Storage bucket named chat-media in the Supabase dashboard.
-- For a quick prototype, make the bucket public. For production, use private
-- storage with signed URLs and storage RLS policies.

-- Realtime:
-- In Supabase Dashboard -> Database -> Replication, enable Realtime for public.messages.
